---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      no-extend-native:
        enabled: false
      no-extra-semi:
        enabled: false
      wrap-iife:
        enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- dist/
- node_modules/
- test/
